### ISSUE TITLE
Windows C (hash link) target is not working

### ISSUE THREAD

**Issue by MiloHX** [armory3d/armory#1046]
Cannot build project with Windows C (Hash Link) target:

![image](https://user-images.githubusercontent.com/17811339/50013864-4c7efe80-fffd-11e8-948d-3ca46868deae.png)

**Comment by luboslenco** [comment]
Please use the 'stable' 0.5 version for now, lots of stuff is wip right now in git version.

**Comment by MiloHX** [comment]
Tested it again with 0.6 Alpha. the export works, VS project can be built without error, but whenever I tried to run the .exe it crashed immediately.

**Comment by luboslenco** [comment]
Pushed one more [fix](https://github.com/armory3d/iron/commit/160ce6dc6c901cb26e6a89e1753933795ea19e06), your [Paddle Strike](https://github.com/MiloHX/Paddle_Strike) now runs as well! Fits into 988KB zipped when exported.:) Implementing sound to go..

**Comment by MiloHX** [comment]
Yay it actually works this time other than no sound! Thank you @luboslenco !

Also for some reason the Vec4.lerp() is running in different speed in each build type, HTML5 run slowest, Krom run faster and HL build run lightning fast. You will notice this by comparing the title particles fade out time. Is it correct behavior? I could add compiler flag to use different value for each build to compensate if it is the way to go.

I also found some menu effect is not working in HL build, probably due to floating point, will fix that.

**Comment by MiloHX** [comment]
@luboslenco, After some thought, the problem is not the Vec4.lerp() itself, it is the because it is placed in function `colorShifting()` which is for shader use: `Uniforms.externalVec3Links.push(colorShifting);`
I suspect that the functions in `externalXXXLinks` are called without considering the locked frame rate (for this case, 60fps), which explained why the Vec4.lerp() in HL build runs the fastest since it is the fastest build type and has the best "true" framerate.
I am not sure if it is bug or something that developer need to consider. I should use a timer to control the fade out or any animation and avoid using lerp(), so that it will not be tied to frame rate.

**Comment by MiloHX** [comment]
@luboslenco OK another finding, in my machine, the GPU usage is considerably higher in HL build (~50%) than the Krom build (~30%). It seems strange since HL should be much more efficient.
Both are quite high for this game (minimum graphics), so there is a very large room to improve.

**Comment by MiloHX** [comment]
@luboslenco Ah for some reason it is unchecked. Thanks! now it is much better with ~5% GPU usage, and the lerp problem is gone too.

**Comment by luboslenco** [comment]
Fixed audio at https://github.com/Kode/Kha/pull/968.
Kha is now using Haxe 4 rc1, opened HashLink update patch at https://github.com/Kode/Kha/pull/984.

**Comment by MiloHX** [comment]
hi @luboslenco should I do some manual update to apply the fixes? After update with updater I got these errors when trying to publish the paddle strike project with HL:
![image](https://user-images.githubusercontent.com/17811339/52573850-f8a26180-2e55-11e9-8479-904dfeda8762.png)

Besides that, publishing with Krom build still have no sound; Set the sound quality to 1.0 still crash (#1047). So I guess all these fixes are not taking effect yet if I use updater. Maybe there will be a new build soon?

**Comment by luboslenco** [comment]
Hm will investigate thanks for notify and yes new build shortly.

**Comment by MiloHX** [comment]
I am happy to report that HL build is OK now with sound!
Sound of Krom build is also working (still delayed though)
but set sound quality to 1.0 then play with Krom, the game still crashed.

**Comment by luboslenco** [comment]
Super cool to hear! Will tackle the remaining two issues at https://github.com/armory3d/armory/issues/1047 and https://github.com/armory3d/armory/issues/1055.
