### ISSUE TITLE
android - Can't read ogg sound > current github dev build 27/09/19

### ISSUE THREAD

**Issue by onelsonic** [armory3d/armory#1412]
Targeting android with the last dev build 27/09/19
the APK is sent correctly to the device but when I add some sounds the App is crashing.
Sound do not work currently.

I can see the file is correctly inside the APK app under : \assets 
but still getting the following errors : 

	2019-09-27 17:03:13.172 24556-24577/tech.kode.kore I/Kinc: Starting KoreHL
	2019-09-27 17:03:13.184 24556-24577/tech.kode.kore W/libOpenSLES: class OutputMix interface 0 requested but unavailable MPH=43
	2019-09-27 17:03:13.188 24556-24577/tech.kode.kore I/libOpenSLES: Emulating old channel mask behavior (ignoring positional mask 0x3, using default mask 0x3 based on channel count of 2)
	2019-09-27 17:03:13.191 24556-24577/tech.kode.kore W/AudioTrack: AUDIO_OUTPUT_FLAG_FAST denied by client; transfer 1, track 44100 Hz, output 48000 Hz
	2019-09-27 17:03:13.193 24556-24577/tech.kode.kore I/AudioTrack: FastTrack denied resize maxNoti fc 590, new 882, enable throttle
	2019-09-27 17:03:13.193 24556-24577/tech.kode.kore D/AudioTrack: Client defaulted notificationFrames to 590 for frameCount 1772
	2019-09-27 17:03:13.195 24556-24577/tech.kode.kore I/AudioTrack: updateAudioTranstionLength FadeIn[0] FadeOut[0] FadeInRing[0]
	2019-09-27 17:03:13.357 24556-24577/tech.kode.kore D/libGLESv2: STS_GLApi : DTS, ODTC are not allowed for Package : tech.kode.kore
	2019-09-27 17:03:13.404 24556-24556/tech.kode.kore D/ViewRootImpl@b0db4f[KoreActivity]: Relayout returned: old=[0,0][1080,2220] new=[0,0][1080,2220] result=0x1 surface={valid=true 491733553152} changed=false
	2019-09-27 17:03:15.096 24556-24577/tech.kode.kore D/hl: Uncaught exception: SysError(Can't read theme000_sdt.ogg)
	2019-09-27 17:03:15.097 24556-24577/tech.kode.kore V/threaded_app: android_app_destroy!
	2019-09-27 17:03:15.116 24556-24556/tech.kode.kore I/zygote64: System.exit called, status: 0
	2019-09-27 17:03:15.116 24556-24556/tech.kode.kore I/AndroidRuntime: VM exiting with result code 0, cleanup skipped.

**Comment by DarthVernus** [comment]
File.getBytes(filename) does not work (Kha\backends\KoreHL\kha\korehl\Sound.hx line:21).
Check this code (Kha\Backends\KoreHL\kha\LoaderImpl.hx):
```
	public static function loadBlobFromDescription(desc: Dynamic, done: Blob -> Void, failed: AssetError -> Void) {
		// done(new Blob(File.getBytes(desc.files[0])));
		var size = 0;
		var bytes = kore_file_contents(StringHelper.convert(desc.files[0]), size);
		done(new Blob(@:privateAccess new haxe.io.Bytes(bytes, size)));
	}
```
- it's work. Sound.hx must be fixed by that way.

**Comment by onelsonic** [comment]
Hi @DarthVernus how did you manage to fix the Sound.hx. for android ?
I've been playing with the code you suggested without success.

**Comment by DarthVernus** [comment]
@onelsonic 
Kha\Backends\KoreHL\kha\LoaderImpl.hx:
```
public static function loadSoundFromDescription(desc: Dynamic, done: kha.Sound -> Void, failed: AssetError -> Void) {
		//done(new kha.korehl.Sound(desc.files[0]));
		var filename:String = desc.files[0];
		if (filename.endsWith(".wav")) {
			done(new kha.korehl.Sound(filename));
		}
		else if (filename.endsWith(".ogg")) {
			var size = 0;
			var bytes = kore_file_contents(StringHelper.convert(filename), size);
			done(new kha.korehl.Sound(filename, @:privateAccess new haxe.io.Bytes(bytes, size)));
		}
		else {
			done(new kha.korehl.Sound(filename));
		}
	}
```
Kha\backends\KoreHL\kha\korehl\Sound.hx:
```
function initOgg(filename: String, bytes:haxe.io.Bytes = null) {
		//compressedData = File.getBytes(filename);
		compressedData = bytes;
	}
	
	public function new(filename: String, bytes:haxe.io.Bytes = null) {
		super();
		if (filename.endsWith(".wav")) {
			initWav(filename);
		}
		else if (filename.endsWith(".ogg")) {
			initOgg(filename, bytes);
		}
		else {
			trace("Unknown sound format: " + filename);
		}
	}
```

**Comment by onelsonic** [comment]
thanks it works👍 (had to add the "using StringTools;") 
after a lot of tests on android here what I found : 
for a 2Mb .ogg file both functions work fine, 
the one using the bytes size and the one without but then

- without the bytes size the file loads in approx. 2sec
- with the bytes size the file loads in approx. 17sec
any reason why retreiving the size of the file?

--------
I tried the below and it works for both .wav and .ogg in 2sec :

Sound.hx :

	function initSound(filename: String) {
		uncompressedData = new kha.arrays.Float32Array();
		var dataSize = new kha.arrays.Uint32Array(1);
		var data = kore_sound_init_wav(StringHelper.convert(filename), dataSize.getData(), length);
		uncompressedData.setData(data, dataSize[0]);
		dataSize.free();
	}
	
	public function new(filename: String, bytes:haxe.io.Bytes = null) {
		super();
		initSound(filename);
	}

LoaderImpl.hx :

	public static function loadSoundFromDescription(desc: Dynamic, done: kha.Sound -> Void, failed: AssetError -> Void) {
		//done(new kha.korehl.Sound(desc.files[0]));
		var filename:String = desc.files[0];
		done(new kha.korehl.Sound(filename));
	}

**Comment by Sanva** [comment]
Hi!

It looks like this error is still present in Kha — I've tested the last proposed solution, simply making the changes in `Sound.hx` proposed in the last comment (as `LoaderImpl.hx` is the same, or at least looks the same to me) and they work.

@onelsonic , may you make a pull request with this change to Kode/Kha? — or I can do it myself, as you wish, but I thought you may want to have the honor :wink: .

[ @luboslenco ] Or we could move this issue to Kha for discussion — I'm not even remotely qualified to tell if this code is completely right or not (I'm not a multimedia developer, just a web one), it just also work in my case.

**Comment by knowledgenude** [comment]
I removed the reference from mine report, but this can help people facing the issue with ogg in Android:  https://github.com/armory3d/armory/issues/1686
