### ISSUE TITLE
"Uncaught TypeError: g.getFloat32" in run time, whith out config "Binary  Scene Data"

### ISSUE THREAD

**Issue by SaxonGao-SZ** [armory3d/armory#2376]
**Description**

![image](https://user-images.githubusercontent.com/37361895/140295235-33f4386f-efd0-4dd9-995b-12c5f0f83e6c.png)
Error infomation:
```
Uncaught TypeError: g.getFloat32 is not a function
    at armory_trait_physics_bullet_PhysicsWorld.createPhysics (kha.js:4826)
    at new armory_trait_physics_bullet_PhysicsWorld (kha.js:4793)
    at Function.Type.createInstance (kha.js:200)
    at Function.iron_Scene.createTraitClassInstance (kha.js:8263)
    at Function.iron_Scene.createTraits (kha.js:8175)
    at kha.js:8411
    at Function.iron_data_Data.getSceneRaw (kha.js:9213)
    at iron_Scene.addScene (kha.js:8410)
    at kha.js:7958
    at Function.iron_data_Data.getWorld (kha.js:9149)
```
**To Reproduce**
**Step 1:** unchecked `Armory Exporter / Data / Binary  Scene Data`  like this:
![image](https://user-images.githubusercontent.com/37361895/140295730-7d1c5c2e-e19e-438f-bd5b-0d871001e8a9.png)

**Step 2:**  `clean -> build -> Publish `  H5 game
**Step 3:** Run http-server in game root path, and open game in browser

**Expected behavior**
What you expected to happen.

**System**
Blender: 2.93.4
Armory: 202110
OS: Win10 Pro
Graphics card: GTX 1660

**Test File**
*(drag & drop the zipped .blend file here)*

**Comment by MoritzBrueckner** [comment]
This could be the same reason as with https://github.com/armory3d/iron/pull/142, it also happens with accessing irradiance values for example, so there are numerous places where this error seems to happen. I wonder if this is a Haxe bug, because it wasn't always the case.... Something with abstracts (which don't exist at runtime) in combination with the `Dynamic` type seems to be broken, or it was broken before and is now fixed and that's why the error happens.

**Comment by tong** [comment]
Json.parse returns `Array<Float>` where `Float32Array` is expected but the cast is not happening when accessing the values.
Wondering too what changed for this to happen.

**Comment by SaxonGao-SZ** [comment]
Is any solution to this problem? For some reason, I need using the .json file to publish, not .arm file.

**Comment by SaxonGao-SZ** [comment]
This problem still exists in the 202111 release. Does it mean I have to wait until 202112 release to solve this problem?

**Comment by MoritzBrueckner** [comment]
> Is any solution to this problem? For some reason, I need using the .json file to publish, not .arm file.

There is, similar to https://github.com/armory3d/iron/pull/142. You'll have to find the places in the code where these errors occur and then cast the problematic variable into a `Float32Array`. The error however seems to be a symptom of a slightly larger issue, so that would probably be just a workaround.

@tong Do you have an assumption whether this was caused by updating Haxe or by the new Kha arrays?

> This problem still exists in the 202111 release. Does it mean I have to wait until 202112 release to solve this problem?

Yes, unless there is a fix soon, then you could update to the newest Git version. You will be noticed when there is a fix because this issue will probably be closed then :)

**Comment by tong** [comment]
I've tried with haxe 4.2.0 with same results (below 4.2 isn't working anymore), therefore my bet is on kha.arrays.

**Comment by tong** [comment]
To further break down this problem:
This works on krom, but not on html5:
```haxe
var a : Array<Float> = [1.0, 2.3];
var b : kha.arrays.Float32Array = a;
trace(b[0]);
```

`Array<Float> should be kha.arrays.Float32Array`

**Comment by MoritzBrueckner** [comment]
Maybe this is because `Float32Array` is an abstract over `js.lib.Float32Array` [on krom](https://github.com/armory3d/Kha/blob/78e640e83d79191ea3ddcf75a0609b130262f9d9/Backends/Krom/kha/arrays/Float32Array.hx#L5) and that seems to support implicit casting, but on html5 it is an abstract over the custom extern class `ByteArray`.

However I don't know if this is really the same issue, as in you case the compiler doesn't want to unify `Array<Float>` with `Float32Array` whereas this issue seems to be caused by the fact that the compiler doesn't know that some value is `Float32Array`. The problems might be connected though...

**Comment by QuantumCoderQC** [comment]
> To further break down this problem: This works on krom, but not on html5:
> 
> ```hx
> var a : Array<Float> = [1.0, 2.3];
> var b : kha.arrays.Float32Array = a;
> trace(b[0]);
> ```
> 
> `Array<Float> should be kha.arrays.Float32Array`

I could not get this to work on both Krom and HTML5. I am using the latest version of the SDK. I think this issue is most likely due to what @MoritzBrueckner mentioned above.

**Comment by MoritzBrueckner** [comment]
> Json.parse returns `Array<Float>` where `Float32Array` is expected but the cast is not happening when accessing the values.
Wondering too what changed for this to happen.

I gave this issue another go and I think I now have an idea what exactly changed: In the past, Kha arrays on both html5 and Krom were abstracts over the typed javascript arrays (e.g. `js.lib.Float32Array`) which supports the `[]` syntax. Thus, the array get/set functions were pretty straightforward and generated js code that used the native `[]` syntax:

https://github.com/Kode/Kha/blob/77e8cf0554dc67643aecf5b975fc3d78f1b7f9df/Backends/HTML5/kha/arrays/Float32Array.hx#L16-L24
```haxe
@:arrayAccess
public inline function set(index: Int, value: FastFloat): FastFloat {
	return this[index] = value;
}

@:arrayAccess
public inline function get(index: Int): FastFloat {
	return this[index];
}
```

This means that even though we were working with typed arrays on the Haxe side, it probably didn't matter at all for javascript whether the values were actually a plain `Array<Float>` since the array access worked in the same way. How the values were read from memory was the job of JS and not of the generated JS code.

Now it's important to notice what @ tong wrote: "Json.parse returns `Array<Float>`". And that was always the case.

Today, where the arrays are abstracts over byte arrays, the `[]` syntax is no longer used in the generated JS code but instead the type-specific get/set functions (`getFloat32()` etc.) are used. Thus, it suddenly matters with which kind of array we're working since we can't rely on JS anymore to resolve the type clash that was (invisibly, thanks to `[]`) existing all the time.

---

As for a solution, I tried adding `@:from` methods to the Kha array abstracts to implicitely cast from `Array<Float>` (by copying the values), but for some reason the methods weren't called and I think it's because it's only a compile-time thing and json.parse() returns a dynamic value.

Another approach could be to manually convert (copy) the arrays after loading the json. However this is of course slower and it probably needs a macro to reliably figure out to what typed array to convert. So it may make more sense to encode the array type somehow (e.g. element 0 defines the type in some way) and then we know the target type. For this it could be worth comparing the performance of the default json.parse() + reflection + conversion with https://github.com/nadako/hxjsonast, which could reduce some of the time lost by performing reflection on the parsed data.
