### ISSUE TITLE
Play Action node does not work with linked action

### ISSUE THREAD

**Issue by donalffons** [armory3d/armory#393]
There is a locally defined action and a linked one in this scene.

![image](https://user-images.githubusercontent.com/33040347/33525907-6ba82b62-d838-11e7-8ad0-489eed427f34.png)

While the locally defined one plays as it should, the linked action gives the following error:
![image](https://user-images.githubusercontent.com/33040347/33525924-bf5fbb3a-d838-11e7-80ec-40170bbb71dd.png)

[linkedactionbug.zip](https://github.com/armory3d/armory/files/1524777/linkedactionbug.zip)

**Comment by luboslenco** [comment]
Should be fixed now https://github.com/armory3d/armory/commit/21b3ebf0b3de9270a1f4d9c5814ad9202092bf97.

**Comment by donalffons** [comment]
Cool. That works now in the example. I ran into a similar problem with linked armature actions. The armature is defined locally. The armature action is linked from armature.blend into main.blend:
![image](https://user-images.githubusercontent.com/33040347/33573407-fdd5e67a-d935-11e7-9b33-108ce8e3fd71.png)

results in this error:
![image](https://user-images.githubusercontent.com/33040347/33573440-1c1d6bb2-d936-11e7-9619-22c4c335ead6.png)

[linkedarmaturebug.zip](https://github.com/armory3d/armory/files/1528598/linkedarmaturebug.zip)

**Comment by luboslenco** [comment]
Oh noes, it seems to work here as-is. Wonder what is going on, looks like updater did the job since the original example works for you now, and armory should now also auto-clean after updating. I will recheck on another machine.

**Comment by donalffons** [comment]
Just tried: Updated Armory, started with an empty folder, downloaded the file from here, cleaned the project. Still the same bug. I'll try with a newly downloaded armory tonigt.

**Comment by luboslenco** [comment]
- Can you spot any errors in the console when you update?
- Check the armsdk/armory/blender/arm/make_logic.py file in your SDK, [line 145](https://github.com/armory3d/armory/blob/master/blender/arm/make_logic.py#L145)
should be:
`inp_name = 'new armory.logicnode.StringNode(this, "' + str(inp.get_default_value()) + '")'`
If it's this, updater failed:
`inp_name = 'new armory.logicnode.StringNode(this, "' + str(inp.default_value) + '")'`
I am seeing the same error with the latter(older) line. If that is the case I hope updater spits some error so I can fix it.:)

**Comment by donalffons** [comment]
1. I started Armory (the same 'old' version, not a newly downloaded one)
2. I went to user preferences / armory and hit Update SDK
3. Here is the console output from blender. There seems to be no error
[Blender Console Log.txt](https://github.com/armory3d/armory/files/1534203/Blender.Console.Log.txt)

The git client on my computer actually sows me up-to-date files with a green marker and out-of-date files with a red one. There is obviously an issue with the updater.
![image](https://user-images.githubusercontent.com/33040347/33649060-a8a0fc9e-da5c-11e7-9feb-7e88d294577e.png)

(The contents of make_logic.py is as in your second line, i.e. `inp_name = 'new armory.logicnode.StringNode(this, "' + str(inp.default_value) + '")'`. )

**Comment by donalffons** [comment]
That's strange... Even after the updater said it did update a file, it is unchanged on my hard drive.

**Comment by donalffons** [comment]
...I get the following error when I hit 'Restore SDK':
![image](https://user-images.githubusercontent.com/33040347/33651355-d3242d02-da65-11e7-9a63-4ddb84c05a67.png)

**Comment by donalffons** [comment]
If I hit 'Restore SDK' first and then 'Update SDK', it updates correctly.

**Comment by luboslenco** [comment]
Apparently I did not include the latest updater in windows build. 😶 🔫 Fixing..

**Comment by donalffons** [comment]
If that's the root of all evil, then it was totally worth it :) -

**Comment by donalffons** [comment]
Do I have to re-download Armory to fix the updater issue or just hit 'update SDK'? I would appreciate it if you would let me know, when that's done.

**Comment by luboslenco** [comment]
@donalffons sorry, wanted to do more testing to not cause further trouble to you.:)

To fix the updater (hopefully for good now!), copy the newest `armory.py` from [here](https://raw.githubusercontent.com/armory3d/armory/master/blender/addon/armory.py) into `Armory/2.79/scripts/addons/armory.py` on your machine.

This basically updates the armory add-on itself which contains the updater. The new v01b builds on itch.io have this change pre-applied. Afterwards starting Blender and hitting `Update SDK` should work as expected. The add-on version displayed in preferences should be 11.5.0.

Once the updater is finally reliable, I will add possibility to auto-update this `armory.py` file as well.

**Comment by donalffons** [comment]
Don't worry about troubling me ;). I tried the new updater (11.5.0) three times. First it deleted the complete 'Armory' folder, then the 'Iron' folder and now again the 'Armory' folder. I guess I should grab the updated build from itch.io and try it from there :).
Thanks for all your great work on this project!

**Comment by luboslenco** [comment]
Hm, the updater should work like this:
- On the first update - rename the original `armory/` and `iron/` folders into `armory_backup/`, `iron_backup/`, these are then used for the `Restore SDK`.
- If backups are already created, remove existing `armory/` and `iron/` folders.
- Finally clone the latest armory and iron repositories from github.

Deleting the older repos should be fine but looks like it skipped the last step to re-clone the latest ones. Hopefully starting from clean v01b will fare better.

**Comment by donalffons** [comment]
Works perfectly now :)!
