### ISSUE TITLE
Node search does not work in b28

### ISSUE THREAD

**Issue by Criticalphil** [armory3d/armory#644]
Hi i just installed armory3d sdk manually and the node search function does not work, everything else seems to work except the search.

if i use the blender.exe which comes with the download the search works, am i doing something wrong?

i don't really want multiple blenders that is why i installed it manually.

**Comment by AdityaSrivastava2819** [comment]
Same with me...

**Comment by luboslenco** [comment]
Noticed the logic node search is broken in armory_b28 version as well, investigating..

**Comment by AdityaSrivastava2819** [comment]
Okay, thanks a lot. I love how Armory is getting along. I believe when it's
done, it'll be on par with UE4. Thanks for all you hardwork.

Aditya

**Comment by adriansnetlis** [comment]
Confirmed that logic node search doesn't work for me too (v0.4 b28).

**Comment by luboslenco** [comment]
Added a working search button in 0.6alpha.

**Comment by SumGaea** [comment]
Hi, this issue is back on Lubuntu 19.04 with icth.io 0.6 base and SDK updated from the addon button a couple of days ago. Looks like this -
![201905sdk_LinuxBrokenNodeSearch](https://user-images.githubusercontent.com/23420988/57750924-a30c7800-7716-11e9-9572-9e5277d745ca.png)
FWIW, before I used to have two search boxes, one of which worked.

**Comment by luboslenco** [comment]
@SumGaea if you download the latest Blender build then the search should work again, sorry for inconvenience.. I should be able to finally pack fresh Armory builds soon.

**Comment by SumGaea** [comment]
Thank you @luboslenco, it's working well here now. New builds aren't so critical for me. Updating the SDK via itch.io 0.6 then copying the SDK folder and armory.py into the latest Blender is pretty painless. Might be good to document as another simple upgrade path.
